//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float4x4 gFixedView;               // Offset:  384 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  448 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  460 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  464 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  472 Size:     8 [unused]
//   float gNearZ;                      // Offset:  480 Size:     4 [unused]
//   float gFarZ;                       // Offset:  484 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  488 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  492 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  496 Size:    16 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  512
//       float FalloffStart;            // Offset:  524
//       float3 Direction;              // Offset:  528
//       float FalloffEnd;              // Offset:  540
//       float3 Position;               // Offset:  544
//       float SpotPower;               // Offset:  556
//
//   } gLights[16];                     // Offset:  512 Size:   768 [unused]
//
// }
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16 [unused]
//   float3 gFresnelR0;                 // Offset:   16 Size:    12 [unused]
//   float gRoughness;                  // Offset:   28 Size:     4 [unused]
//   float4x4 gMatTransform;            // Offset:   32 Size:    64
//
// }
//
// cbuffer cbSkinned
// {
//
//   float4x4 gBoneTransforms[131];     // Offset:    0 Size:  8384
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// cbPerObject                       cbuffer      NA          NA     CB0            cb0      1 
// cbPass                            cbuffer      NA          NA     CB1            cb1      1 
// cbMaterial                        cbuffer      NA          NA     CB2            cb2      1 
// cbSkinned                         cbuffer      NA          NA     CB3            cb3      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// WEIGHTS                  0   xyzw        3     NONE   float   xyz 
// BONEINDICES              0   xyzw        4     NONE    uint   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
vs_5_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[0:0][8], immediateIndexed, space=0
dcl_constantbuffer CB1[1:1][20], immediateIndexed, space=0
dcl_constantbuffer CB2[2:2][4], immediateIndexed, space=0
dcl_constantbuffer CB3[3:3][523], dynamicIndexed, space=0
dcl_input v0.xyz
dcl_input v1.xyz
dcl_input v2.xy
dcl_input v3.xyz
dcl_input v4.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xy
dcl_temps 6
dcl_indexableTemp x0[4], 4
mov x0[0].x, v3.x
mov x0[1].x, v3.y
mov x0[2].x, v3.z
add r0.x, -v3.x, l(1.000000)
add r0.x, r0.x, -v3.y
add r0.x, r0.x, -v3.z
mov x0[3].x, r0.x
mov r0.xyz, v0.xyzx
mov r0.w, l(1.000000)
mov r1.xyz, l(0,0,0,0)
mov r2.xyz, l(0,0,0,0)
mov r3.x, l(0)
loop 
  ige r2.w, r3.x, l(4)
  breakc_nz r2.w
  mov r2.w, x0[r3.x + 0].x
  ineg r3.z, r3.x
  ult r4.xyz, r3.xxxx, l(1, 2, 3, 0)
  and r5.y, r3.z, r4.y
  iadd r3.xy, r3.xxxx, l(1, -3, 0, 0)
  movc r5.z, r4.y, l(0), r3.y
  ieq r5.w, r4.z, l(0)
  mov r5.x, r4.x
  and r4.xyzw, r5.xyzw, v4.xyzw
  or r3.yz, r4.yywy, r4.xxzx
  or r3.y, r3.z, r3.y
  ishl r3.y, r3.y, l(2)
  dp4 r4.x, r0.xyzw, CB3[3][r3.y + 0].xyzw
  dp4 r4.y, r0.xyzw, CB3[3][r3.y + 1].xyzw
  dp4 r4.z, r0.xyzw, CB3[3][r3.y + 2].xyzw
  mad r1.xyz, r2.wwww, r4.xyzx, r1.xyzx
  dp3 r4.x, v1.xyzx, CB3[3][r3.y + 0].xyzx
  dp3 r4.y, v1.xyzx, CB3[3][r3.y + 1].xyzx
  dp3 r4.z, v1.xyzx, CB3[3][r3.y + 2].xyzx
  mad r2.xyz, r2.wwww, r4.xyzx, r2.xyzx
endloop 
dp3 r0.x, r2.xyzx, r2.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, r2.xyzx
mov r1.w, l(1.000000)
dp4 r2.x, r1.xyzw, CB0[0][0].xyzw
dp4 r2.y, r1.xyzw, CB0[0][1].xyzw
dp4 r2.z, r1.xyzw, CB0[0][2].xyzw
dp4 r2.w, r1.xyzw, CB0[0][3].xyzw
dp3 o2.x, r0.xyzx, CB0[0][0].xyzx
dp3 o2.y, r0.xyzx, CB0[0][1].xyzx
dp3 o2.z, r0.xyzx, CB0[0][2].xyzx
dp4 o0.x, r2.xyzw, CB1[1][16].xyzw
dp4 o0.y, r2.xyzw, CB1[1][17].xyzw
dp4 o0.z, r2.xyzw, CB1[1][18].xyzw
dp4 o0.w, r2.xyzw, CB1[1][19].xyzw
mov r0.xy, v2.xyxx
mov r0.z, l(1.000000)
dp3 r1.x, r0.xyzx, CB0[0][4].xywx
dp3 r1.y, r0.xyzx, CB0[0][5].xywx
dp3 r1.z, r0.xyzx, CB0[0][6].xywx
dp3 r1.w, r0.xyzx, CB0[0][7].xywx
dp4 o3.x, r1.xyzw, CB2[2][2].xyzw
dp4 o3.y, r1.xyzw, CB2[2][3].xyzw
mov o1.xyz, r2.xyzx
ret 
// Approximately 61 instruction slots used
